<<<<<<< Updated upstream
# fly.toml app configuration file generated for kernelsanders on 2024-11-03T21:31:48-05:00
=======
# fly.toml app configuration file generated for kernelsanders on 2024-11-07T10:38:22-05:00
>>>>>>> Stashed changes
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kernelsanders'
primary_region = 'mia'
kill_signal = "SIGINT"
kill_timeout = 5

[build]
<<<<<<< Updated upstream
  [build.args]
    GO_VERSION = '1.16'

[env]
  PORT = '8080'
=======
  command = "./main"
>>>>>>> Stashed changes

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  BOT_USERNAME = "KernelSandersBot"
  PORT = "8080"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
